using System.Collections.Generic;
using RWCustom;
using UnityEngine;

namespace SlugBrain
{
    class InputSpoofer
    {
        public InputSpoofer()
        {
            _inputPackage = new Player.InputPackage();
            _inputBuffer = new List<HeldInput>();
        }

        /// <summary>
        /// Combines automated inputs registered via <see cref="PushNewInput(Player.InputPackage)"/>
        /// with player inputs. Can also be used for combining sets of auto inputs.
        /// </summary>
        /// <param name="orig">Inputs generated by the player.</param>
        public Player.InputPackage ModifyInputs(Player.InputPackage orig)
        {
            orig.x = Mathf.Clamp(orig.x + _inputPackage.x, -1, 1);
            orig.y = Mathf.Clamp(orig.y + _inputPackage.y, -1, 1);

            orig.jmp = orig.jmp || _inputPackage.jmp;
            orig.mp = orig.mp || _inputPackage.mp;
            orig.pckp = orig.pckp || _inputPackage.pckp;
            orig.thrw = orig.thrw || _inputPackage.thrw;

            return orig;
        }

        /// <summary>
        /// Registers automated inputs to be combined with player inputs.
        /// </summary>
        public void PushNewInput(Player.InputPackage newInput)
        {
            _inputPackage = newInput;

            List<int> toRemove = new List<int>();

            for (int i = 0; i < _inputBuffer.Count; i++)
            {
                HeldInput newBufferItem = new HeldInput(_inputBuffer[i].input, _inputBuffer[i].frames - 1);

                if (newBufferItem.frames <= 0)
                {
                    toRemove.Add(i);
                }
                else
                {
                    _inputPackage = ModifyInputs(newBufferItem.input);
                }

                _inputBuffer[i] = newBufferItem;
            }

            foreach (int i in toRemove) _inputBuffer.RemoveAt(i);
        }

        public void HoldNewInput(Player.InputPackage newInput, int frames)
        {
            _inputBuffer.Add(new HeldInput(newInput, frames));
        }

        public void Jump(int frames)
        {
            HoldNewInput(new Player.InputPackage() { jmp = true }, frames);
        }

        public void ClearInputExceptBuffer()
        {
            _inputPackage = new Player.InputPackage();
        }

        public void ClearAllInput()
        {
            _inputBuffer.Clear();
            ClearInputExceptBuffer();
        }


        private Player.InputPackage _inputPackage;
        private readonly List<HeldInput> _inputBuffer;

        public int X => _inputPackage.x;
        public int Y => _inputPackage.y;
        public IntVector2 Dir => new IntVector2(X, Y);
        public bool IsJumping => _inputPackage.jmp;
        public bool IsLookingAtMap => _inputPackage.mp;
        public bool IsGrabbing => _inputPackage.pckp;
        public bool IsThrowing => _inputPackage.thrw;


        public struct HeldInput
        {
            public HeldInput(Player.InputPackage input, int frames)
            {
                this.input = input;
                this.frames = frames;
            }

            public readonly Player.InputPackage input;
            public readonly int frames;
        }

    }
}
